### ISSUE TITLE
What's the difference between two configs?

### ISSUE THREAD

**Issue by keenkit** [vishal3152/HyperledgerFabric-Java-Client#1]
Hi..
Which one I should use? It seems the `network-config_sample.json` does not work for me (I am running fabric 1.2.0 network), it shows error: `A client organization must be specified`.

So I have to use the `network-config_sample.json2`?
I do not quite understand. Thanks.

**Comment by keenkit** [comment]
Looks like the `network-config_sample.json2` runs upon `grpcs` other than `grpc` with TLS enalbed, is it an available case? Or can you update it and make it workable please? Thanks.

**Comment by vishal3152** [comment]
Hi, The client is tested for network-config-sample2.json. I have removed the other one. I can help if you can share your network config file, **mask your private keys** before sharing.
===========================
If TLS is enabled then grpcs is must. It is equivalent to https. You cant have tls enabled connection over http.
